version: '3.8'

services:
  # Product Service
  product-service:
    build: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product-db:3306/product_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql-product-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-order-db:3306/order_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql-order-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  # Product Database
  mysql-product-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=product_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Order Database
  mysql-order-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=order_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-product-data:
  mysql-order-data:

networks:
  ecommerce-network:
    driver: bridge
